services:
  api:
    build:
      context: .
      args:
        INSTAGRAM_USER_ACCESS_TOKEN: "IGAA6ZCreQkLt9BZAE0xZAzNqSFFfZA09QRUdtUklxSG1rS093ajhUOGpLTUJoUURJWmxNVERqOUt0ZAXlHaGQwczRiTVV3RWw4aWZASZAWlQVW5PSFdqSF8yTjBoQkprVFZAkdGgyTTdReTd6NVhaZAzJ1MEU0S3FCLV85SGZAWaTU2U1RYVQZDZD"
        GOOGLE_CLOUD_PROJECT: "shopassist-agentic"
        GOOGLE_CLOUD_LOCATION: "us-central1"
        GOOGLE_GENAI_USE_VERTEXAI: "true"
        RAPIDAPI_KEY: "3f27f73bf7msh172fe90d50dcc8cp170ab1jsn9fce497f54c6"
    ports:
      - "8080:8080"
    volumes:
      - ./credentials:/app/credentials
    environment:
      - FIREBASE_SERVICE_ACCOUNT_PATH=/app/credentials/service-account.json
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account.json
      - RAPIDAPI_KEY=3f27f73bf7msh172fe90d50dcc8cp170ab1jsn9fce497f54c6
      - INSTAGRAM_USER_ACCESS_TOKEN=IGAA6ZCreQkLt9BZAE0xZAzNqSFFfZA09QRUdtUklxSG1rS093ajhUOGpLTUJoUURJWmxNVERqOUt0ZAXlHaGQwczRiTVV3RWw4aWZASZAWlQVW5PSFdqSF8yTjBoQkprVFZAkdGgyTTdReTd6NVhaZAzJ1MEU0S3FCLV85SGZAWaTU2U1RYVQZDZD
      - GOOGLE_CLOUD_PROJECT=shopassist-agentic
      - GOOGLE_CLOUD_LOCATION=us-central1
      - GOOGLE_GENAI_USE_VERTEXAI=true
      - FIREBASE_PROJECT_ID=shopassist-agentic
    env_file:
      - .env.local 