version: '3'

services:
  api:
    build:
      context: .
      args:
        - INSTAGRAM_USER_ACCESS_TOKEN=${INSTAGRAM_USER_ACCESS_TOKEN}
        - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
        - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
        - GOOGLE_GENAI_USE_VERTEXAI=${GOOGLE_GENAI_USE_VERTEXAI}
    ports:
      - "8080:8080"
    volumes:
      - ./credentials:/app/credentials
    environment:
      - FIREBASE_SERVICE_ACCOUNT_PATH=/app/credentials/service_account.json
    env_file:
      - .env.local 